- dataset_name: radon
  model_name: radon_hiearchical_intercept2_hoprior
  posterior_name: radon_hiearchical_intercept2_hoprior
- dataset_name: radon_mn
  model_name: radon_hiearchical_intercept2_hoprior
  posterior_name: radon_mn_hiearchical_intercept2_hoprior
- dataset_name: radon
  model_name: radon_partial_pooling2_hoprior
  posterior_name: radon_partial_pooling2_hoprior
- dataset_name: radon_mn
  model_name: radon_partial_pooling2_hoprior
  posterior_name: radon_mn_partial_pooling2_hoprior
- dataset_name: radon
  model_name: radon_variable_intercept_slope2_hoprior
  posterior_name: radon_variable_intercept_slope2_hoprior
- dataset_name: radon_mn
  model_name: radon_variable_intercept_slope2_hoprior
  posterior_name: radon_mn_variable_intercept_slope2_hoprior
- dataset_name: radon
  model_name: radon_hiearchical_intercept2
  posterior_name: radon_hiearchical_intercept2
- dataset_name: radon_mn
  model_name: radon_hiearchical_intercept2
  posterior_name: radon_mn_hiearchical_intercept2
- dataset_name: radon
  model_name: radon_partial_pooling2
  posterior_name: radon_partial_pooling2
- dataset_name: radon_mn
  model_name: radon_partial_pooling2
  posterior_name: radon_mn_partial_pooling2
- dataset_name: radon
  model_name: radon_variable_intercept_slope2
  posterior_name: radon_variable_intercept_slope2
- dataset_name: radon_mn
  model_name: radon_variable_intercept_slope2
  posterior_name: radon_mn_variable_intercept_slope2
